// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rmarchingcubes_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// marching_cubes
marching_cubes_output marching_cubes(arma::cube data, arma::vec x, arma::vec y, arma::vec z, double iso);
RcppExport SEXP _rmarchingcubes_marching_cubes(SEXP dataSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP isoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type iso(isoSEXP);
    rcpp_result_gen = Rcpp::wrap(marching_cubes(data, x, y, z, iso));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmarchingcubes_marching_cubes", (DL_FUNC) &_rmarchingcubes_marching_cubes, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmarchingcubes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
