# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marching_cubes <- function(data, x, y, z, iso) {
    .Call('_rmarchingcubes_marching_cubes', PACKAGE = 'rmarchingcubes', data, x, y, z, iso)
}

